services:
  db:
    image: mysql:9.2
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=form2_db
      - MYSQL_USER=form2user
      - MYSQL_PASSWORD=userpassword
    ports:
      - 3306:3306
    volumes:
      - ./sqlfiles/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: mysqladmin ping -h localhost

  adminer:
    depends_on:
      - db
    image: adminer
    ports:
      - 8080:8080

  server:
    restart: on-failure
    image: python-api-form2
    volumes:
      - ./server:/server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - 8000:8000
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=form2_db
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=rootpassword
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn server:app --proxy-headers --host 0.0.0.0 --port 8000

  react:
    image: react
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      - REACT_APP_SERVER_URL=http://localhost:8000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/server
    command: npm start 