version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: form2-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: form2app
      MYSQL_USER: form2user
      MYSQL_PASSWORD: form2password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - form2-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  adminer:
    image: adminer:4.8.1
    container_name: form2-adminer
    ports:
      - "8080:8080"
    networks:
      - form2-network
    depends_on:
      - mysql

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: form2-server
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: form2app
      MYSQL_USER: form2user
      MYSQL_ROOT_PASSWORD: rootpassword
      ADMIN_EMAIL: loise.fenoll@ynov.com
      ADMIN_PASSWORD: PvdrTAzTeR247sDnAZBr
    ports:
      - "8000:8000"
    networks:
      - form2-network
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./server:/server

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: form2-frontend
    environment:
      REACT_APP_SERVER_URL: http://localhost:8000
    ports:
      - "3000:3000"
    networks:
      - form2-network
    depends_on:
      - server
    volumes:
      - ./src:/app/src
      - ./public:/app/public

volumes:
  mysql_data:

networks:
  form2-network:
    driver: bridge 