name: Build, Test and Deploy Form2 Application

env:
  REACT_APP_SERVER_URL: ${{ secrets.REACT_APP_SERVER_URL }}

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build_test:
    permissions:
      contents: write
      pull-requests: write
      pages: write
      id-token: write
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run unit tests
        run: npm run test:unit

      - name: Build Docker images
        run: |
          docker compose --version
          docker compose build

      - name: Start Docker stack
        run: |
          docker compose up -d
          echo "Waiting for services to be ready..."
          sleep 60

      - name: Check services health
        run: |
          echo "Checking MySQL..."
          for i in {1..10}; do
            if docker compose exec mysql mysqladmin ping -h localhost --silent; then
              echo "MySQL is ready!"
              break
            fi
            echo "MySQL not ready, waiting... ($i/10)"
            sleep 10
          done
          
          echo "Checking Frontend..."
          for i in {1..10}; do
            if curl -f http://localhost:3000 >/dev/null 2>&1; then
              echo "Frontend is ready!"
              break
            fi
            echo "Frontend not ready, waiting... ($i/10)"
            sleep 10
          done
          
          echo "Checking Backend..."
          for i in {1..10}; do
            if curl -f http://localhost:8000 >/dev/null 2>&1; then
              echo "Backend is ready!"
              break
            fi
            echo "Backend not ready, waiting... ($i/10)"
            sleep 10
          done
          
          echo "Services status check completed"

      - name: Show Docker logs for debugging
        run: |
          echo "=== Frontend logs ==="
          docker compose logs frontend || echo "No frontend logs"
          echo "=== Backend logs ==="
          docker compose logs server || echo "No backend logs"
          echo "=== MySQL logs ==="
          docker compose logs mysql || echo "No MySQL logs"

      - name: Run E2E tests with Cypress
        uses: cypress-io/github-action@v6
        with:
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 180
        continue-on-error: true

      - name: Stop Docker stack
        run: docker compose down
        if: always()

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
        if: always()

      - name: Generate documentation
        run: npm run jsdoc

      - name: Build React application
        run: npm run build
        env:
          REACT_APP_SERVER_URL: ${{ env.REACT_APP_SERVER_URL }}

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy_pages:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build_test

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 