name: CI/CD Pipeline

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

env:
  REACT_APP_SERVER_URL: ${{ secrets.REACT_APP_SERVER_URL }}

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Nadjide/form2-app
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

      - name: Generate documentation
        run: npm run jsdoc

      - name: Build application
        run: npm run build
        env:
          REACT_APP_SERVER_URL: ${{ env.REACT_APP_SERVER_URL }}

  e2e:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Start Docker Compose
        run: |
          docker compose up -d
          echo "Waiting for services to be ready..."
          sleep 60

      - name: Check services health
        run: |
          echo "Checking MySQL..."
          for i in {1..10}; do
            if docker compose exec mysql mysqladmin ping -h localhost --silent; then
              echo "MySQL is ready!"
              break
            fi
            echo "MySQL not ready, waiting... ($i/10)"
            sleep 10
          done
          
          echo "Checking Frontend..."
          for i in {1..10}; do
            if curl -f http://localhost:3000 >/dev/null 2>&1; then
              echo "Frontend is ready!"
              break
            fi
            echo "Frontend not ready, waiting... ($i/10)"
            sleep 10
          done
          
          echo "Checking Backend..."
          for i in {1..10}; do
            if curl -f http://localhost:8000 >/dev/null 2>&1; then
              echo "Backend is ready!"
              break
            fi
            echo "Backend not ready, waiting... ($i/10)"
            sleep 10
          done
          
          echo "Services status check completed"

      - name: Run Cypress E2E tests
        uses: cypress-io/github-action@v6
        with:
          wait-on: 'http://localhost:3000, http://localhost:8000'
          wait-on-timeout: 180

      - name: Stop Docker Compose
        run: docker compose down
        if: always() 